services:
  
  db:
    image: postgres:16-alpine
    container_name: 2026_db
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=2026_db
    ports:
      - "5432:5432"
    volumes:
      - ./infra/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data

  queue:
    image: redis:7-alpine
    container_name: 2026_queue
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  scheduler:
    container_name: 2026_scheduler
    build:
      context: ./services/scheduler
    command: python src/main.py
    depends_on:
      - queue
    environment:
      - PYTHONUNBUFFERED=1
    restart: always

  scraper:
    container_name: 2026_scraper
    build:
      context: ./services/scraper
    command: python src/main.py
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - queue
      - db
    restart: always

volumes:
  pgdata:
  redisdata: