services:

  db:
    image: postgres:16-alpine
    container_name: 2026_db
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=2026_db
    ports:
      - "5432:5432"
    volumes:
      - ./infra/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data

  queue:
    image: redis:7-alpine
    container_name: 2026_queue
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  scheduler:
    container_name: 2026_scheduler
    build:
      context: ./services/scheduler
    command: python -m src.main
    environment:
      - PYTHONUNBUFFERED=1
    dns:
      - 8.8.8.8
    depends_on:
      - queue
    restart: always

  scraper:
    container_name: 2026_scraper
    build:
      context: ./services/scraper
    command: python -m src.main
    environment:
      - PYTHONUNBUFFERED=1
    dns:
      - 8.8.8.8
    volumes:
      - ./shared:/app/shared
    depends_on:
      - queue
      - db
    restart: always

  processor:
    container_name: 2026_processor
    build:
      context: ./services/processor
    command: python -m src.main
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    dns:
      - 8.8.8.8
    volumes:
      - ./shared:/app/shared
    depends_on:
      - queue
      - db
    restart: always

  aggregator:
    container_name: 2026_aggregator
    build:
      context: ./services/aggregator
    command: python -m src.main
    environment:
      - PYTHONUNBUFFERED=1
    dns:
      - 8.8.8.8
    volumes:
      - ./shared:/app/shared
    depends_on:
      - queue
      - db
    restart: always

  web_api:
    container_name: 2026_web_api
    build:
      context: ./services/web_api
    command: python -m src.main
    environment:
      - PYTHONUNBUFFERED=1
    dns:
      - 8.8.8.8
    volumes:
      - ./shared:/app/shared
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always

  jupyter_research:
    container_name: 2026_jupyter_research
    build:
      context: ./research
    ports:
      - "8888:8888"
    volumes:
      - ./research:/app
    environment:
      - JUPYTER_TOKEN=mentor2026

  pgadmin:
    container_name: 2026_pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mentor.local
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata:
  redisdata:
